///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Sprite Color FX.
//
// Copyright (c) Ibuprogames <hello@ibuprogames.com>. All rights reserved.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

namespace SpriteColorFX
{
  /// <summary>
  /// This code was automatically generated by 'Color Ramp Tool', do not modify!
  /// </summary>
  public enum SpriteColorRampPalettes
  {
    Fire1 = 0,
    Fire2 = 1,
    Water1 = 2,
    Gem1 = 3,
    Air1 = 4,
    Crystal1 = 5,
    Wood1 = 6,
    Wood2 = 7,
    Stone1 = 8,
    Stone2 = 9,
    Metal1 = 10,
    Metal2 = 11,
  }
}
